---
- hosts: all
  remote_user: "{{ ansible_user }}"
  become: true

  tasks:
  - name: Install Docker
    yum:
      name: docker
      state: present

  - name: Ensure Docker is running
    service:
      name: docker
      state: started

  - name: Install pip for python
    yum:
      name: python-pip
      state: present

  - name: Install docker-py
    pip:
      name: docker-py
      state: present

  - name: Install Hasura
    docker_container:
      name: graphql-engine
      image: hasura/graphql-engine:v1.0.0-beta.3
      state: started
      pull: true
      ports:
        - "8080:8080"
      env:
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
        HASURA_GRAPHQL_DATABASE_URL: "{{ POSTGRES_URL }}"

  - name: Nginx reverse proxy
    template:
      src: "nginx.config.j2"
      dest: "/etc/nginx/conf.d/{{ SERVICE_URL }}.conf"
      mode: 0640
      owner: "{{ ansible_user }}"

  - name: Restart Nginx
    service:
      name: nginx
      state: restarted