subscription ordersBetween($after: timestamptz!, $before: timestamptz!) {
  orders(
    where: {
      detail_type: { _eq: "GoodCity" },
      state: { _neq: "draft" },
      order_transport: {
        scheduled_at: {
            _gt: $after,
            _lt: $before
          }
        }
      }
  ) {
    id
    code
    state
    people_helped
    updated_at
    booking_type_id
    orders_packages_aggregate {
      aggregate {
        count
      }
		}
    orders_packages {
      package {
        id,
        state
      }
    }
    goodcity_requests_aggregate{
      aggregate {
        count
      }
    }
    order_transport {
      scheduled_at
      transport_type
    }
  }
}