version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

aliases:
  - defaults: &defaults
      docker:
        - image: cimg/node:14.2.0
      working_directory: ~/code
  - &restore-repo-cache
      key: v1-goodcity-dashboard-{{ .Environment.CIRCLE_SHA1 }}
  - &restore-yarn-cache
      keys:
        - v1-goodcity-dashboard-packages-{{ checksum "yarn.lock" }}
  - &save-yarn-cache
      key: v1-goodcity-dashboard-packages-{{ checksum "yarn.lock" }}
      paths:
        - node_modules
        - ~/.cache/yarn
  - &yarn
    |
      yarn install --non-interactive --cache-folder ~/.cache/yarn --frozen-lockfile

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v1-goodcity-dashboard-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/code

  package_dependencies:
    <<: *defaults
    steps:
      - restore_cache: *restore-repo-cache
      - restore_cache: *restore-yarn-cache
      - run: *yarn
      - save_cache: *save-yarn-cache

  www_build:
    <<: *defaults
    steps:
      - restore_cache: *restore-repo-cache
      - restore_cache: *restore-yarn-cache
      - run:
          name: Parcel build
          command: |
            NODE_ENV=production yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  www-deploy:
    <<: *defaults
    steps:
      - restore_cache: *restore-repo-cache
      - attach_workspace:
          at: ~/code
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          name: Copy files to Azure
          command: |
            az storage blob upload-batch -s ./dist -d '$web/dashboard-goodcity' --account-name goodcitystorage --overwrite
            az storage blob delete-batch -s '$web'  --account-name goodcitystorage --pattern 'dashboard-goodcity/*' --if-unmodified-since `date -u -d "1 hour ago" '+%Y-%m-%dT%H:%MZ'`

workflows:
    version: 2
    build_and_bundle:
      jobs:
        - checkout_code 
        - package_dependencies:
            requires:
              - checkout_code
        - www_build:
            requires:
              - package_dependencies
            filters:
              branches:
                only: /^(master)$/
        - www-deploy:
            requires:
              - www_build
            filters:
              branches:
                only: /^(master)$/
