version: 2

aliases:
  - defaults: &defaults
      docker:
        - image: circleci/node:carbon
      working_directory: ~/code
  - &restore-repo-cache
      key: v1-goodcity-dashboard-{{ .Environment.CIRCLE_SHA1 }}
  - &restore-yarn-cache
      keys:
        - v1-goodcity-dashboard-packages-{{ checksum "yarn.lock" }}
  - &save-yarn-cache
      key: v1-goodcity-dashboard-packages-{{ checksum "yarn.lock" }}
      paths:
        - node_modules
        - ~/.cache/yarn
  - &yarn
    |
      yarn install --non-interactive --cache-folder ~/.cache/yarn --frozen-lockfile

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v1-goodcity-dashboard-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/code

  package_dependencies:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

  test_cases:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - run:
          name: Run tests
          command: yarn test

  www_build:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - run:
          name: Parcel build
          command: |
            NODE_ENV=production yarn build:azure
      - persist_to_workspace:
          root: .
          paths:
            - dist

  www-deploy:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - attach_workspace:
          at: ~/code
      - run:
          name: Download AZCOPY
          command: |
              wget -O azcopyv10.tar https://azcopyvnext.azureedge.net/release20190301/azcopy_linux_amd64_10.0.8.tar.gz
              tar -xf azcopyv10.tar --strip-components=1
      - run:
          name: Copy files to Azure
          command: |
            ./azcopy sync ./dist "$AZURE_STORAGE_URL_PROD" --recursive=true --delete-destination=true

workflows:
    version: 2
    build_and_bundle:
      jobs:
        - checkout_code
        - package_dependencies:
            requires:
              - checkout_code
        - test_cases:
            requires:
              - package_dependencies
        - www_build:
            requires:
              - package_dependencies
              - test_cases
            filters:
              branches:
                only: /^(master)$/
        - www-deploy:
            requires:
              - www_build
            filters:
              branches:
                only: /^(master)$/
